apiVersion: v1
kind: Deployment
metadata:
  name: maingo

  spec:
    selector:
      matchLabels:
        app: maingo
    template:
      metadata:
        labels:
          app: maingo
      spec:
        containers:
        - name: maingo
          image: img-maingo-deployment
          ports:
          - containerPort: 8000
