substitutions:
          _K8_DESAFIO_GO_VERSION: 1.0.0
steps:
- id: "Rodando o push da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/k8s-desafio-go:latest'
  - '.'

- id: "Rodando teste unitario"
  name: 'gcr.io/cloud-builders/docker'
  args: ['run','-t','--name','myteste','gcr.io/$PROJECT_ID/k8s-desafio-go:latest','go','test']

- id: "Fazendo o building image from Dockerfile.prod"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/go-main:$SHORT_SHA','-f','Dockerfile.prod','.']
 
- id: "Ajustando o deployment file - k8s"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-maingo-deployment#gcr.io/$PROJECT_ID/go-main:$SHORT_SHA#g' ./k8s/maingo/deployment.yaml > ./k8s/maingo/deployment-new.yaml;
      cat ./k8s/maingo/deployment-new.yaml
- id: "Deploying k8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/app/deployment-new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

images:
- 'gcr.io/$PROJECT_ID/k8s-desafio-go:latest'
tags: ['cloud-builders-go-desafio']
